### PR TITLE
Kc/cantilever

### PR DESCRIPTION
**Pull request by KristofferC**
Wat...

image

Plz find bug when u have time.

PR is on top of grid branch

### CODE REVIEW

**Comment by fredrikekre** [comment]
Nice!

**Comment by KristofferC** [comment]
Base.LinAlg.PosDefException

when I do cholesky factorization.. something is fishy

**Comment by KristofferC** [comment]
image

Same code, just changed to tetrahedrons. Wtf

**Comment by KristofferC** [comment]
image

This is the boundary conditions. Looks a bit weird...

**Comment by KristofferC** [comment]
The Tetrahedron is pos def as well

**Comment by fredrikekre** [comment]
is it the same if you use CellScalarValues?

**Comment by KristofferC** [comment]
Will check.

**Comment by KristofferC** [comment]
You decide

image

**Comment by fredrikekre** [comment]
At least its kinda beautiful :)

**Comment by KristofferC** [comment]
BTW, it seems that too many surfaces are includes in the boundary sets for the tetrahedron case.

**Comment by KristofferC** [comment]
Ill just compare with some other stuff tomorrow. Now I'm gonna watch "Finding Nemo".

**Comment by KristofferC** [comment]
2D seems ok..

image

image

**Comment by KristofferC** [comment]
The only thing I can think about is that there is something strange with the mesh for 3d cubes.. But you had run that previously.

**Comment by KristofferC** [comment]
Or wait..

**Comment by KristofferC** [comment]
Noooooo... I had order 1 quadrature rule for cubes.

**Comment by KristofferC** [comment]
image

**Comment by fredrikekre** [comment]
I was gonna say that it might be the integration :p

**Comment by KristofferC** [comment]
The only thing that feels awkward in that notebook is the extraction of nodes from the surface sets so I can put dirichlet boundary conditions on them.

**Comment by fredrikekre** [comment]
Let me check it out when I reach a computer :)

**Comment by KristofferC** [comment]
It's chill brah.

**Comment by KristofferC** [comment]
Added neumann boundary conditions for a traction on the right side instead of dirichlet and now also testing notebooks. There are a few awkward things stil in the notebook for the neumann loop.

**Comment by KristofferC** [comment]
This PR is a bit all over the place so I will cherry-pick out parts into smaller, more concise PRs.

**Comment by fredrikekre** [comment]
Alright, haven't been online that much this weekend, will review the upcoming PR's then!

> BTW, it seems that too many surfaces are includes in the boundary sets for the tetrahedron case. They are "one layer too deep".

I think that may have been messed up when we changed the order of the shape functions for the `RefTetrahedron` in 3D. Will fix!

**Comment by fredrikekre** [comment]
Something useful here?

**Comment by KristofferC** [comment]
The adding nodesets and cellsets functionality maybe?

**Comment by fredrikekre** [comment]
They are in master already

**Comment by KristofferC** [comment]
oh ok.

**Comment by fredrikekre** [comment]
#125

**Pull request closed without merging**
