### PR TITLE
Fix hyperelasticity example

### LINKED ISSUE #250: ERROR: LoadError: UndefVarError: assemble not defined
in hyperelastic model, error:
`
ERROR: LoadError: UndefVarError: assemble not defined`

Best

### PR DESCRIPTION
**Pull request by KristofferC**
Closes #250 

Also adds a note to the files in the top level example folder that they might be out of date.

### CODE REVIEW

**Comment by KristofferC** [comment]
Why would Tensors not be found in the doc process?

**Comment by fredrikekre** [comment]
Its not here: https://github.com/KristofferC/JuAFEM.jl/blob/master/docs/Project.toml

**Comment by KristofferC** [comment]
Oh, my project files etc are completely messed up here...

**Comment by KristofferC** [comment]
Closed by https://github.com/KristofferC/JuAFEM.jl/pull/256?

**Comment by fredrikekre** [comment]
Lets just add the README.

**Pull request merged**
