### PR TITLE
Fix for new conversion in ContMechTensors

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by KristofferC** [comment]
Will merge when the other PR is merged

**Comment by fredrikekre** [comment]
bump to restart testing, should pass now that `ContMechTensors` are upgraded.

**Comment by KristofferC** [comment]
To restart you can rebase on the new master and then force push to this branch.

**Comment by fredrikekre** [comment]
But there is no new master :p

**Comment by KristofferC** [comment]
Oh yeah, `git commit --amend date=now` then on this commit and force push.

**Comment by KristofferC** [comment]
looks good, merge yourself

**Comment by fredrikekre** [comment]
Life level: `PhD student` that qualifies me as collaborator? :p

**Pull request merged**
