### PR TITLE
build docs in testscript, run in stric mode

### LINKED ISSUE #114: Run doc build in testscript

### PR DESCRIPTION
**Pull request by fredrikekre**
fix #114

### CODE REVIEW

**Comment by fredrikekre** [comment]
`strict` mode seems to fail because of missing doc strings in the docs. And also warns cause we don't document all the functions in `ContMechTensors` and `WriteVTK`, because we `@reexport` them.

**Comment by fredrikekre** [comment]
This is what travis fails for, a warning about a `@simd`-loop...

```
!! Test error in the following code block in '/home/travis/.julia/v0.5/JuAFEM/src/quadrature.jl':

        julia> QuadratureRule{2, RefTetrahedron}(1)

        JuAFEM.QuadratureRule{2,JuAFEM.RefTetrahedron,Float64}([0.5],ContMechTensors.Tensor{1,2,Float64,2}[[0.333333,0.333333]])

        

        julia> QuadratureRule{1, RefCube}(:lobatto, 2)

        JuAFEM.QuadratureRule{1,JuAFEM.RefCube,Float64}([1.0,1.0],ContMechTensors.Tensor{1,1,Float64,1}[[-1.0],[1.0]])

    in expression:

        QuadratureRule{1, RefCube}(:lobatto, 2)

    expected:

        JuAFEM.QuadratureRule{1,JuAFEM.RefCube,Float64}([1.0,1.0],ContMechTensors.Tensor{1,1,Float64,1}[[-1.0],[1.0]])

    returned:

        WARNING: could not attach metadata for @simd loop.

        JuAFEM.QuadratureRule{1,JuAFEM.RefCube,Float64}([1.0,1.0],ContMechTensors.Tensor{1,1,Float64,1}[[-1.0],[1.0]])
```

**Comment by fredrikekre** [comment]
Locally I get this instead:

```jl
LoadError: LoadError: ------ ErrorException ------------------ Stacktrace (most recent call last)

 [1] — include_from_node1(::String) at loading.jl:488 (repeats 2 times)

 [2] — (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at <missing>:0

 [3] — #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at Documenter.jl:159

 [4] — cd(::Documenter.##2#3{Documenter.Documents.Document}, ::String) at file.jl:59

 [5] — dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at Selectors.jl:164

 [6] — runner(::Type{Documenter.Builder.RenderDocument}, ::Documenter.Documents.Document) at Builder.jl:202

`makedocs` encountered an error. Terminating build

```

**Comment by fredrikekre** [comment]
Seems like the `@simd` warning is failing the build. Passes locally though. What to do here?
And why isn't the same thing happening with `ContMechTensors`?

**Comment by fredrikekre** [comment]
Ideas for this?
Maybe try to build docs last? And hope the warnings are done?

**Comment by fredrikekre** [comment]
sweet, it worked 🎉

**Comment by KristofferC** [comment]
nice

**Comment by fredrikekre** [comment]
it confuses me that the same problem doesn't appear in `ContMechTensors`...

**Pull request merged**
