### PR TITLE
rename DirichletBoundaryConditions to ConstraintHandler

### PR DESCRIPTION
**Pull request by fredrikekre**
Matches `DofHandler` more nicely, and is more general if we extend with other type of constraints.

### CODE REVIEW

**Comment by KristofferC** [comment]
Sounds good!

**Comment by lijas** [comment]
Dbcs and other constraints are treated quite differently, so maybe it will be difficult to implement all constraint in a single ConstraintHandler?

**Comment by fredrikekre** [comment]
The current situation is just a bit awkward IMO:
```julia
dbcs = DirichletBoundaryConditions(dh)
dbc = DirichletBoundaryCondition(:u, faceset, (x, t) -> 0)
add!(dbcs, dbc)
```
Perhaps we can go back to the pre-#159 style, but rename `DirichletBoundaryConditions` to `Dirichlet`. That would look like:
```julia
dbc = Dirichlet(dh)
add!(dbc, :u, faceset, (x, t) -> 0)    <- We don't create a DirichletBoundaryCondition here, only internally
```

**Comment by fredrikekre** [comment]
But something like
```julia
ch = ConstraintHandler(dh)
dbc = Dirichlet(:u, faceset, (x, t) -> 0)
add!(ch, dbc)
```
Looks very nice...

**Comment by fredrikekre** [comment]
Interesting failure only Windows64-bit:
```
 !! failed to run `@setup` block.
LoadError("string", 1, ErrorException("syntax: invalid escape sequence")) [src\examples\heat_equation.md]
```

**Pull request merged**
