### PR TITLE
Remake QuadratureRule

### LINKED ISSUE #74: QuadratureRule creation
I propose we change the QuadratureRule constructor to use `dim` and `refshape` as parameters.

Now: 
```jl
julia> QuadratureRule(Dim{2}, RefCube(), 2)
JuAFEM.QuadratureRule{2,Float64}([1.0,1.0,1.0,1.0],ContMechTensors.Tensor{1,2,Float64,2}[[-0.57735,-0.57735],[0.57735,-0.57735],[-0.57735,0.57735],[0.57735,0.57735]])
```

Desired:
```jl
julia> QuadratureRule{2, RefCube}(2)
JuAFEM.QuadratureRule{2,Float64}([1.0,1.0,1.0,1.0],ContMechTensors.Tensor{1,2,Float64,2}[[-0.57735,-0.57735],[0.57735,-0.57735],[-0.57735,0.57735],[0.57735,0.57735]])
```

will have conflicts with the changes in #73 I think so maybe change after that is merged. Or I might include it in that PR, if it helps with the coding of `FEFaceValues` :)

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix #74

### CODE REVIEW

**Comment by fredrikekre** [comment]
btw, why is `QuadratureRule` a `type` and not an `immutable`?

**Comment by KristofferC** [comment]
Should probably be an immutable yes.

**Comment by KristofferC** [comment]
How bad are the docs now compared to the truth :p

**Comment by fredrikekre** [comment]
Not that bad! I have at least updated the docstrings :) But the links and stuff are not working I guess :)

**Comment by fredrikekre** [comment]
This solved #61 too.

**Pull request merged**
