### PR TITLE
remove boundscheck on f when inbounds assembling

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by fredrikekre** [comment]
KrylovMethods seems capped

**Comment by KristofferC** [comment]
Should probably swap to IterativeSolvers

**Comment by KristofferC** [comment]
Passes on 0.7 so perhaps good to go?

**Comment by fredrikekre** [comment]
Did this actually change something? We have https://github.com/KristofferC/JuAFEM.jl/blob/6b340e6744cec28530e30f83b2fc907980524034/src/assembler.jl#L62-L63 already

**Comment by KristofferC** [comment]
Yes but I don't think the call from where I made the change make it applies the inbounds. At least I saw allocations before this change but I can double check.

**Pull request merged**
