### PR TITLE
relax matrix in assembler

### PR DESCRIPTION
**Pull request by fredrikekre**
```jl
julia> ke = rand(SMatrix{4,4,Float64});

julia> typeof(ke) <: Matrix{Float64}
false

julia> typeof(ke) <: AbstractMatrix{Float64}
true
```

### CODE REVIEW

**Comment by KristofferC** [comment]
`edof` could probably be an abstractvector as well.

**Comment by fredrikekre** [comment]
Derp, can not index into a `SMatrix` anyway, so pretty useless to have `ke` as an `SMatrix`.

**Comment by KristofferC** [comment]
You can use an `MMatrix`.

**Comment by fredrikekre** [comment]
Oh, nice!

Seems like it is defined for SMatrix too, just not working?

```jl
julia> ke = zero(SMatrix{4,4,Float64});

julia> @which ke[1,1] = 1.0
setindex!{SM<:StaticArrays.StaticArray{T,2}}(m::SM, val, i1::Integer, i2::Integer) at /home/fredrik/.julia/v0.5/StaticArrays/src/indexing.jl:226
```

**Comment by KristofferC** [comment]
`SMatrix` is stored on the stack so you can basically only have `setindex` without the `!` that returns a new object.

**Comment by fredrikekre** [comment]
Yea, but there is a `setindex!` defined in the code is what I meant.

**Comment by fredrikekre** [comment]
Btw, `StaticArrays` implements indexing with tuples, which is pretty nice! I always create a vector from the tuple and index with that before :)

**Comment by KristofferC** [comment]
Yes, but it might be removed because it should probably be in base. But you can also index with an `SVector` to get another `SVector`.

**Comment by fredrikekre** [comment]
> Not sure it will matters for performance though.

Seems to be a bit slower, at least if you use a predefined matrix

**Comment by fredrikekre** [comment]
AV is on vacation

**Pull request merged**
