### PR TITLE
add function space and gauss rule for tetraheder

### PR DESCRIPTION
**Pull request by KristofferC**
We going 3d baby

### CODE REVIEW

**Comment by KristofferC** [comment]
seems to work:

image

**Comment by KristofferC** [comment]
Tests fail because Tk.jl is failing on master.

**Comment by fredrikekre** [comment]
Nice!

**Comment by KristofferC** [comment]
First 3d analysis with juafem?? ;)

3d_slip

**Comment by fredrikekre** [comment]
Looking good!

**Pull request merged**
